// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SumRequest struct {
	FirstNumber          int32    `protobuf:"varint,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	SecondNumber         int32    `protobuf:"varint,2,opt,name=second_number,json=secondNumber,proto3" json:"second_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{0}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *SumRequest) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type SumResponse struct {
	SumResult            int32    `protobuf:"varint,1,opt,name=sum_result,json=sumResult,proto3" json:"sum_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{1}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetSumResult() int32 {
	if m != nil {
		return m.SumResult
	}
	return 0
}

type PrimeNumberDescompositionRequest struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberDescompositionRequest) Reset()         { *m = PrimeNumberDescompositionRequest{} }
func (m *PrimeNumberDescompositionRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDescompositionRequest) ProtoMessage()    {}
func (*PrimeNumberDescompositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{2}
}

func (m *PrimeNumberDescompositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberDescompositionRequest.Unmarshal(m, b)
}
func (m *PrimeNumberDescompositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberDescompositionRequest.Marshal(b, m, deterministic)
}
func (m *PrimeNumberDescompositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberDescompositionRequest.Merge(m, src)
}
func (m *PrimeNumberDescompositionRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberDescompositionRequest.Size(m)
}
func (m *PrimeNumberDescompositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberDescompositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberDescompositionRequest proto.InternalMessageInfo

func (m *PrimeNumberDescompositionRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PrimeNumberDescompositionResponse struct {
	PrimeFactor          int64    `protobuf:"varint,1,opt,name=prime_factor,json=primeFactor,proto3" json:"prime_factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberDescompositionResponse) Reset()         { *m = PrimeNumberDescompositionResponse{} }
func (m *PrimeNumberDescompositionResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDescompositionResponse) ProtoMessage()    {}
func (*PrimeNumberDescompositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{3}
}

func (m *PrimeNumberDescompositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberDescompositionResponse.Unmarshal(m, b)
}
func (m *PrimeNumberDescompositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberDescompositionResponse.Marshal(b, m, deterministic)
}
func (m *PrimeNumberDescompositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberDescompositionResponse.Merge(m, src)
}
func (m *PrimeNumberDescompositionResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberDescompositionResponse.Size(m)
}
func (m *PrimeNumberDescompositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberDescompositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberDescompositionResponse proto.InternalMessageInfo

func (m *PrimeNumberDescompositionResponse) GetPrimeFactor() int64 {
	if m != nil {
		return m.PrimeFactor
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "calculator.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "calculator.SumResponse")
	proto.RegisterType((*PrimeNumberDescompositionRequest)(nil), "calculator.PrimeNumberDescompositionRequest")
	proto.RegisterType((*PrimeNumberDescompositionResponse)(nil), "calculator.PrimeNumberDescompositionResponse")
}

func init() {
	proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor_7f42938f8c8365cf)
}

var fileDescriptor_7f42938f8c8365cf = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xc3, 0x30,
	0x14, 0xc0, 0xad, 0xc3, 0x81, 0xaf, 0x55, 0x30, 0x87, 0xa9, 0x03, 0x61, 0xad, 0x97, 0x1d, 0xe6,
	0x14, 0xbd, 0x88, 0x47, 0x95, 0x1d, 0x45, 0x5a, 0x4f, 0x5e, 0x4a, 0x1b, 0xdf, 0xa0, 0xd0, 0x34,
	0x31, 0x2f, 0xf1, 0xe4, 0x37, 0xf4, 0x4b, 0x89, 0x69, 0x6b, 0x03, 0xa2, 0xee, 0x96, 0xf7, 0xe3,
	0xf7, 0xfe, 0xe4, 0x25, 0x30, 0xe7, 0x45, 0xcd, 0x6d, 0x5d, 0x18, 0xa9, 0xcf, 0x87, 0xa3, 0x2a,
	0xbd, 0x60, 0xa9, 0xb4, 0x34, 0x92, 0xc1, 0x40, 0x92, 0x27, 0x80, 0xcc, 0x8a, 0x14, 0x5f, 0x2d,
	0x92, 0x61, 0x31, 0x44, 0xeb, 0x4a, 0x93, 0xc9, 0x1b, 0x2b, 0x4a, 0xd4, 0x47, 0xc1, 0x2c, 0x98,
	0xef, 0xa4, 0xa1, 0x63, 0x0f, 0x0e, 0xb1, 0x53, 0xd8, 0x23, 0xe4, 0xb2, 0x79, 0xe9, 0x9d, 0x6d,
	0xe7, 0x44, 0x2d, 0x6c, 0xa5, 0x64, 0x01, 0xa1, 0xab, 0x4a, 0x4a, 0x36, 0x84, 0xec, 0x04, 0x80,
	0xac, 0xc8, 0x35, 0x92, 0xad, 0x4d, 0x57, 0x74, 0x97, 0x9c, 0x60, 0x6b, 0x93, 0xdc, 0xc0, 0xec,
	0x51, 0x57, 0x02, 0xdb, 0xe4, 0x7b, 0x24, 0x2e, 0x85, 0x92, 0x54, 0x99, 0x4a, 0x36, 0xfd, 0x64,
	0x13, 0x18, 0x7b, 0x33, 0x8d, 0xd2, 0x2e, 0x4a, 0x56, 0x10, 0xff, 0x91, 0xdb, 0xf5, 0x8f, 0x21,
	0x52, 0x5f, 0x52, 0xbe, 0x2e, 0xb8, 0x91, 0x7d, 0x89, 0xd0, 0xb1, 0x95, 0x43, 0x97, 0x1f, 0x01,
	0x1c, 0xdc, 0x7d, 0xaf, 0x25, 0x43, 0xfd, 0x56, 0x71, 0x64, 0xd7, 0x30, 0xca, 0xac, 0x60, 0x93,
	0xa5, 0xb7, 0xc3, 0x61, 0x5d, 0xd3, 0xc3, 0x1f, 0xbc, 0x6d, 0x98, 0x6c, 0xb1, 0x77, 0x38, 0xfe,
	0x75, 0x2e, 0xb6, 0xf0, 0xf3, 0xfe, 0xbb, 0xfa, 0xf4, 0x6c, 0x43, 0xbb, 0xef, 0x7d, 0x11, 0xdc,
	0xee, 0x3f, 0x47, 0xfe, 0x17, 0x28, 0xc7, 0xee, 0xe1, 0xaf, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x88, 0xa0, 0xa9, 0x21, 0x24, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	PrimeNumberDescomposition(ctx context.Context, in *PrimeNumberDescompositionRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDescompositionClient, error)
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) PrimeNumberDescomposition(ctx context.Context, in *PrimeNumberDescompositionRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDescompositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[0], "/calculator.CalculatorService/PrimeNumberDescomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServicePrimeNumberDescompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_PrimeNumberDescompositionClient interface {
	Recv() (*PrimeNumberDescompositionResponse, error)
	grpc.ClientStream
}

type calculatorServicePrimeNumberDescompositionClient struct {
	grpc.ClientStream
}

func (x *calculatorServicePrimeNumberDescompositionClient) Recv() (*PrimeNumberDescompositionResponse, error) {
	m := new(PrimeNumberDescompositionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	PrimeNumberDescomposition(*PrimeNumberDescompositionRequest, CalculatorService_PrimeNumberDescompositionServer) error
}

// UnimplementedCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (*UnimplementedCalculatorServiceServer) Sum(ctx context.Context, req *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (*UnimplementedCalculatorServiceServer) PrimeNumberDescomposition(req *PrimeNumberDescompositionRequest, srv CalculatorService_PrimeNumberDescompositionServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumberDescomposition not implemented")
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_PrimeNumberDescomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberDescompositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).PrimeNumberDescomposition(m, &calculatorServicePrimeNumberDescompositionServer{stream})
}

type CalculatorService_PrimeNumberDescompositionServer interface {
	Send(*PrimeNumberDescompositionResponse) error
	grpc.ServerStream
}

type calculatorServicePrimeNumberDescompositionServer struct {
	grpc.ServerStream
}

func (x *calculatorServicePrimeNumberDescompositionServer) Send(m *PrimeNumberDescompositionResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDescomposition",
			Handler:       _CalculatorService_PrimeNumberDescomposition_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calculator/calculatorpb/calculator.proto",
}
